---
- name: install pound
  yum: name=Pound enablerepo=epel-testing state=present
  tags:
    - pound
    - packages

- name: configure pound
  template: src="pound.cfg.j2" dest="/etc/pound.cfg" owner=root group=root mode=0644
  notify: restart pound
  tags:
    - pound
    - configuration

- name: create pound log directory
  file: path=/var/log/pound owner=root group=root mode=0700 state=directory
  tags:
    - pound
    - configuration
    - rsyslog

- name: configure rsyslog for pound
  template: src=rsyslog.conf.j2 dest=/etc/rsyslog.d/pound.conf
  tags:
    - pound
    - configuration
    - rsyslog

- name: configure logrotate for pound
  template: src=logrotate.j2 dest=/etc/logrotate.d/pound owner=root group=root mode=0644
  tags:
    - httpd
    - logrotate
    - configuration

- name: ensure pound is enabled and running
  service: name=pound enabled=yes state=started
  tags:
    - pound
    - configuration
    - services

- name: configure firewalld for pound http
  firewalld: zone=public port="{{ pound_http_port }}/tcp" permanent=true state=enabled
  notify: reload firewall
  when: pound_open_http_port and ansible_distribution_major_version|int > 6
  tags:
    - pound
    - firewall
    - configuration

- name: configure firewalld for pound https
  firewalld: zone=public port="{{ pound_https_port }}/tcp" permanent=true state=enabled
  notify: reload firewall
  when: pound_open_https_port and ansible_distribution_major_version|int > 6
  tags:
    - pound
    - firewall
    - configuration
